### ISSUE TITLE
Make icon float like notion 

### ISSUE THREAD

**Issue by KuiyueRO** [cycsd/obsidian-card-note#6]
example:

```css
.markdown-source-view.mod-cm6 .cm-gutters {
	margin-inline-end: unset;
	position: absolute !important;
}
```
