### ISSUE TITLE
position of icon

### ISSUE THREAD

**Issue by AsleepX** [cycsd/obsidian-card-note#9]
![image](https://github.com/cycsd/obsidian-card-note/assets/129823735/f248b954-dce5-427b-ba2f-b15bd32397b2)
Now the icon will occupy the area where the text is written, resulting in inconsistency between the document properties and the width of the writing area, is it possible to have the icon displayed on the left side of the writing area instead of occupying the width of the writing area.

**Comment by cycsd** [comment]
You could set your obsidian-style-settings mentioned in this #6 

```css
.cn-drag-symbol{
    position: absolute;
    left:-30px
}
.markdown-source-view.mod-cm6 .cm-gutters{
    margin-inline-end: unset;
}
```
